apiVersion: environment.cloudbees.com/v1alpha1
kind: GitRepository
metadata:
  name: nac-fm-workshop-2023-2-21-microblog-frontend                             
  namespace: previews
spec:
  url: https://github.com/nac-fm-workshop-2023-2-21/microblog-frontend.git
  apiTokenSecretRef:
    name: beedemo-dev-github-token
  autoCreateContexts:                           
  - default 
  autoUpdateContexts:                           
  - default
